Repository wcmc-its/ReCiter, pull requests merged in 2019-05, with the labels that each got.

#338 Sanitization Utility and miscellaneous changes
  pom.xml
  src/main/java/reciter/algorithm/evidence/targetauthor/TargetAuthorSelection.java
  src/main/java/reciter/algorithm/evidence/targetauthor/department/strategy/DepartmentStringMatchStrategy.java
  src/main/java/reciter/algorithm/evidence/targetauthor/knownrelationship/strategy/KnownRelationshipStrategy.java
  src/main/java/reciter/algorithm/evidence/targetauthor/name/strategy/ScoreByNameStrategy.java
  src/main/java/reciter/algorithm/util/ArticleTranslator.java
  src/main/java/reciter/controller/ReCiterController.java
  src/main/java/reciter/utils/AuthorNameSanitizationUtils.java
  src/test/java/reciter/algorithm/evidence/targetauthor/TargetAuthorSelectionTest.java
  src/test/java/reciter/utils/AuthorNameSanitizationUtilsTest.java
Labels: Bug, enhancement

#339 Name sanitization utility and improve test coverage
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  pom.xml
  src/main/java/reciter/algorithm/evidence/targetauthor/TargetAuthorSelection.java
  src/main/java/reciter/algorithm/evidence/targetauthor/department/strategy/DepartmentStringMatchStrategy.java
  src/main/java/reciter/algorithm/evidence/targetauthor/knownrelationship/strategy/KnownRelationshipStrategy.java
  src/main/java/reciter/algorithm/evidence/targetauthor/name/strategy/ScoreByNameStrategy.java
  src/main/java/reciter/algorithm/util/ArticleTranslator.java
  src/main/java/reciter/controller/ReCiterController.java
  src/main/java/reciter/queue/sqs/AmazonSQSExtendedClientConfig.java
  src/main/java/reciter/utils/AuthorNameSanitizationUtils.java
  src/main/resources/application.properties
  src/test/java/reciter/algorithm/evidence/targetauthor/TargetAuthorSelectionTest.java
  src/test/java/reciter/utils/AuthorNameSanitizationUtilsTest.java
Labels: Bug, Priority, enhancement

#344 Exception error hotfix
  src/main/java/reciter/algorithm/evidence/targetauthor/affiliation/strategy/CommonAffiliationStrategy.java
  src/main/java/reciter/controller/ReCiterController.java
Labels: Bug

#354 Additional org unit synonyms
  src/main/resources/application.properties
Labels: enhancement
